<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.interceptor.CacheErrorHandlerTests" tests="9" skipped="0" failures="0" errors="0" timestamp="2020-04-15T13:43:53" hostname="PandaroiddeiMac.local" time="0.127">
  <properties/>
  <testcase name="clearFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.047"/>
  <testcase name="evictFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.01"/>
  <testcase name="getFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.01"/>
  <testcase name="putFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.01"/>
  <testcase name="getFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.012"/>
  <testcase name="getAndPutFail()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.009"/>
  <testcase name="putFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.007"/>
  <testcase name="evictFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.008"/>
  <testcase name="clearFailProperException()" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.011"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
